# Generated by Django 4.0.2 on 2022-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('author', models.CharField(max_length=100, verbose_name='Autor del curso')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='URL')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
